Enhance `ManifestCoder` for Encoding/Decoding Routine Arguments and Returned Values
sarvalabs/js-moi-sdk pull request #81
Opened 2024-08-22 07:31 UTC by sarvalabs-harshrastogi

# Enhance `ManifestCoder` for Encoding/Decoding Routine Arguments and Returned Values

> [!IMPORTANT]
> This pull request has breaking changes 

This pull request enhances the `ManifestCoder` class by introducing new methods and improvements to existing ones. These changes aim to simplify the process of encoding and decoding routine arguments and returned values, improving the overall developer experience.

**Changes:**

1. **`ElementDescriptor`**:
   - The `ElementDescriptor` class has been relocated from `js-moi-logic` to `js-moi-manifest`.
   - Developers can now instantiate an `ElementDescriptor` object with a manifest object, providing more flexibility and integration with the manifest data.

2. **`ManifestCoder`**:
   - This constructor method now accepts a manifest of type `LogicManifest.Manifest` as input. (**_Breaking Change_**)

3. **`Manifest.encodeArguments`**:
   - This method now supports extracting routine type fields from arguments based on the routine name.
   - It can encode arguments into the POLO format, simplifying the developer experience.
   - The existing functionality remains unaffected, ensuring backward compatibility.

```javascript
const manifest = await loadManifestFromFile("../../manifests/tokenledger.json");
const manifestCoder = new ManifestCoder(manifest);
const args = ["MOI", 100_000_000];
const calldata = manifestCoder.encodeArguments("Seeder", args);
console.log(calldata) // >>> 0x0d6f0665b6019502737570706c790305f5e10073796d626f6c064d4f49
```
4. **`ManifestCoder.decodeArguments`**:
   - This new method enables extracting the type of the returned value from a routine.
   - It can decode the POLO output passed as an argument, facilitating the processing of routine results.

```typescript
const manifest = await loadManifestFromFile("../../manifests/tokenledger.json");
const manifestCoder = new ManifestCoder(manifest);
const outputSerialized = "0x0e1f0305f5e100";
const callsite = "BalanceOf";
const output = manifestCoder.decodeOutput<{ balance: number }>(outputSerialized, callsite);

console.log(output) // >>> { balance: 100000000 }
```

These changes streamline the process of working with routine arguments and returned values within the `ManifestCoder` class.

- closes #62 

## Changes include
- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

## Checklist
- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have tested this code
- [X] I have updated the README and other relevant documents (guides...)

2024-09-04 06:29 UTC, sarvalabs-gokul requested changes

2024-09-24 10:15 UTC, sarvalabs-harshrastogi commented on docs/source/manifest-call-encoder.rst
> +    >> "0x0e4f065...50000"
https://github.com/sarvalabs/js-moi-sdk/pull/81/commits/55762787555e06dd877c8033e379cfc866a7d462

2024-09-24 10:20 UTC, sarvalabs-harshrastogi commented on docs/source/manifest-call-encoder.rst
> +    const args = manifestCoder.decodeOutput(output, callsite);
https://github.com/sarvalabs/js-moi-sdk/pull/81/commits/dfe3aef4f4f9793d019bb6d403a64093bc806c80

2024-09-24 10:23 UTC, sarvalabs-harshrastogi commented on packages/js-moi-manifest/__tests__/abi.test.ts
>      const classDefs = new Map();
No, we ain't using these, thus remove it.

https://github.com/sarvalabs/js-moi-sdk/pull/81/commits/c6eac3d4bd9aa54348664f0b4871c19316b2d47e

2024-10-24 08:33 UTC, merged